name: Lint and Fix

on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: write
    pull-requests: write

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install linters globally
              run: |
                  npm install --global eslint htmlhint stylelint stylelint-config-standard

            - name: Auto-fix CSS
              run: |
                  stylelint "**/*.css" --fix

            - name: Lint JavaScript
              run: eslint "**/*.js" --ignore-pattern eslint.config.js

            - name: Lint HTML
              run: htmlhint "**/*.html"

            - name: Create Pull Request for lint fixes
              uses: peter-evans/create-pull-request@v6
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: "stylelint: auto-fix CSS issues"
                  title: "Stylelint CSS fixes"
                  body: |
                      This PR was automatically created by GitHub Actions after running Stylelint autofixes.
                  branch: stylelint-fixes
                  delete-branch: true